---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(nflreadr)
library(gt)
library(gtExtras)
library(ggimage)
```

```{r}
ftn <- load_ftn_charting(seasons = 2024)

ftn <- ftn %>% select(nflverse_game_id, ftn_play_id: is_qb_fault_sack) %>% rename(game_id = nflverse_game_id, play_id = nflverse_play_id)

```

```{r}
nfl_pbp <- load_pbp(get_current_season())

pbp <- left_join(nfl_pbp, ftn, by = c("game_id", "play_id")) %>% filter(!is.na(ftn_play_id))
```

```{r}
rost <- load_rosters(2024) %>% select(gsis_id, full_name, headshot_url)

teams <- load_teams() %>% select(posteam = team_abbr, espn_logo = team_logo_espn)
```

```{r}
motion <- pbp %>% mutate(is_motion = as.integer(as.logical(is_motion))) %>% filter(special_teams_play == 0) %>% group_by(posteam) %>% summarize(plays = n(), motion = sum(is_motion)) %>% ungroup() %>% mutate(pct = 100*round(motion/plays,3))

motion_epa <- pbp %>% filter(is_motion == T) %>% group_by(posteam) %>% summarize(play = n(), EPA = sum(epa, na.rm = T)) %>% mutate(EPA_play = EPA/play) %>% ungroup() %>% select(posteam, EPA, EPA_play)

motion <- left_join(motion, motion_epa, by = "posteam") %>% left_join(., teams, by = "posteam")
```

```{r}
ggplot(motion, aes(x = EPA_play, y = pct)) + geom_image(aes(image = espn_logo))
```

```{r}
pa <- pbp %>% filter(is_play_action == T, !is.na(passer_player_id), qb_dropback == 1) %>% group_by(gsis_id = passer_player_id) %>% summarize(plays = n(), EPA = sum(epa, na.rm = T)) %>% ungroup() %>% mutate(EPA_play = EPA/plays) %>% filter(plays > 24) %>% left_join(., rost, by = "gsis_id")
```

```{r}
ggplot(pa, aes(x = EPA_play, y = plays)) + geom_image(aes(image = headshot_url)) + geom_vline(xintercept = mean(pa$EPA_play)) + geom_hline(yintercept = mean(pa$plays)) + theme_classic()
```

```{r}
pressure <- pbp %>% filter(n_pass_rushers > 4, !is.na(passer_player_id), qb_dropback == 1, down == 3) %>% group_by(gsis_id = passer_player_id, posteam) %>% summarize(plays = n(), EPA = sum(epa, na.rm = T), sacks = sum(sack)) %>% ungroup() %>% mutate(EPA_play = EPA/plays, sack_rate = 100*round(sacks/plays, 3)) %>% filter(plays > 9) %>% left_join(., rost, by = "gsis_id") %>% left_join(.,teams, by = "posteam")

```

```{r}
logos <- pressure %>% select(name = full_name, headshot_url) %>% deframe()

pressure %>% select(team = espn_logo, name = full_name, plays, EPA_play) %>% arrange(-EPA_play) %>% slice(1:5) %>% gt() %>% text_transform(locations = cells_body(columns = "name"), fn = function(x) {lapply(x, function(x){ gt::html(paste(web_image(url = logos[[x]], height = 50), x))})}) %>% gt_img_rows(columns = team, img_source = "web", height = 50) %>% gt_theme_espn %>% fmt_number(columns = c(EPA_play), decimals = 2) %>% data_color(columns = c(EPA_play), colors = "Greens") %>% opt_table_font(font = list(google_font(name = "Roboto Condensed"), default_fonts())) %>% tab_header(title = "QBs EPA/Play on 3rd Down Facing 5+ Rushers") %>% opt_table_lines()
```

